

export const inventoryItems = [
    {
        "id": "1719460520910",
        "name": "Milk",
        "amountPerUnit": 1,
        "unit": "liters",
        "quantity": 20,
        "costPerUnit": 1.99,
        "whenToOrder": 5,
        "sku": "dairy001",
        "packageType": "carton",
        "supplierName": "DairyFresh",
        "category": "Dairy"
    },
    {
        "id": "1719460520911",
        "name": "Chicken Breast",
        "amountPerUnit": 5,
        "unit": "lbs",
        "quantity": 10,
        "costPerUnit": 7.99,
        "whenToOrder": 8,
        "sku": "meat001",
        "packageType": "bag",
        "supplierName": "PoultryPro",
        "category": "Meat"
    },
    {
        "id": "1719460520912",
        "name": "Frozen Peas",
        "amountPerUnit": 2,
        "unit": "kg",
        "quantity": 15,
        "costPerUnit": 4.99,
        "whenToOrder": 5,
        "sku": "frozen001",
        "packageType": "box",
        "supplierName": "FreezerGoods",
        "category": "Frozen"
    },
    {
        "id": "1719460520913",
        "name": "Red Wine",
        "amountPerUnit": 750,
        "unit": "milliliters",
        "quantity": 25,
        "costPerUnit": 12.99,
        "whenToOrder": 10,
        "sku": "wine001",
        "packageType": "bottle",
        "supplierName": "VineyardSupplies",
        "category": "Wine Cellar"
    },
    {
        "id": "1719460520914",
        "name": "Canned Tuna",
        "amountPerUnit": 200,
        "unit": "grams",
        "quantity": 50,
        "costPerUnit": 2.49,
        "whenToOrder": 10,
        "sku": "canned001",
        "packageType": "can",
        "supplierName": "SeaDelights",
        "category": "Canned"
    },
    {
        "id": "1719460520915",
        "name": "Yogurt",
        "amountPerUnit": 500,
        "unit": "grams",
        "quantity": 30,
        "costPerUnit": 3.99,
        "whenToOrder": 35,
        "sku": "dairy002",
        "packageType": "container",
        "supplierName": "DairyFresh",
        "category": "Dairy"
    },
    {
        "id": "1719460520916",
        "name": "Beef Steaks",
        "amountPerUnit": 4,
        "unit": "lbs",
        "quantity": 10,
        "costPerUnit": 15.99,
        "whenToOrder": 6,
        "sku": "meat002",
        "packageType": "each",
        "supplierName": "PoultryPro",
        "category": "Meat"
    },
    {
        "id": "1719460520917",
        "name": "Apples",
        "amountPerUnit": 1,
        "unit": "kg",
        "quantity": 20,
        "costPerUnit": 2.99,
        "whenToOrder": 25,
        "sku": "fruit001",
        "packageType": "box",
        "supplierName": "BestFruits",
        "category": "Fruits"
    },
    {
        "id": "1719460520918",
        "name": "Butter",
        "amountPerUnit": 200,
        "unit": "grams",
        "quantity": 40,
        "costPerUnit": 3.49,
        "whenToOrder": 10,
        "sku": "dairy003",
        "packageType": "container",
        "supplierName": "DairyFresh",
        "category": "Dairy"
    },
    {
        "id": "1719460520919",
        "name": "Cereal",
        "amountPerUnit": 500,
        "unit": "grams",
        "quantity": 25,
        "costPerUnit": 4.99,
        "whenToOrder": 7,
        "sku": "dry001",
        "packageType": "box",
        "supplierName": "BreakfastClub",
        "category": "Dry Storage"
    }
];

export const suppliers = [
    {
        "supplierID": "001",
        "supplierName": "Best Foods",
        "email": "bestfoods@example.com",
        "phone": "123-456-7890",
        "contractStatus": "active",
        "startDate": "2023-01-01",
        "endDate": "2025-01-01"
    },
    {
        "supplierID": "002",
        "supplierName": "WholeFOODS",
        "email": "wholefoods@example.com",
        "phone": "123-456-7891",
        "contractStatus": "inactive",
        "startDate": "2021-06-15",
        "endDate": "2023-06-15"
    },
    {
        "supplierID": "003",
        "supplierName": "DairyFresh",
        "email": "dairyfresh@example.com",
        "phone": "123-456-7892",
        "contractStatus": "active",
        "startDate": "2022-03-10",
        "endDate": "2024-03-10"
    },
    {
        "supplierID": "004",
        "supplierName": "PoultryPro",
        "email": "poultrypro@example.com",
        "phone": "123-456-7893",
        "contractStatus": "active",
        "startDate": "2023-02-20",
        "endDate": "2025-02-20"
    },
    {
        "supplierID": "005",
        "supplierName": "FreezerGoods",
        "email": "freezergoods@example.com",
        "phone": "123-456-7894",
        "contractStatus": "inactive",
        "startDate": "2020-08-30",
        "endDate": "2022-08-30"
    },
    {
        "supplierID": "006",
        "supplierName": "VineyardSupplies",
        "email": "vineyardsupplies@example.com",
        "phone": "123-456-7895",
        "contractStatus": "active",
        "startDate": "2023-05-01",
        "endDate": "2025-05-01"
    },
    {
        "supplierID": "007",
        "supplierName": "SeaDelights",
        "email": "seadelights@example.com",
        "phone": "123-456-7896",
        "contractStatus": "active",
        "startDate": "2023-07-15",
        "endDate": "2025-07-15"
    },
    {
        "supplierID": "008",
        "supplierName": "BestFruits",
        "email": "bestfruits@example.com",
        "phone": "123-456-7897",
        "contractStatus": "active",
        "startDate": "2023-09-10",
        "endDate": "2025-09-10"
    },
    {
        "supplierID": "009",
        "supplierName": "BreakfastClub",
        "email": "breakfastclub@example.com",
        "phone": "123-456-7898",
        "contractStatus": "inactive",
        "startDate": "2021-11-20",
        "endDate": "2023-11-20"
    },
    {
        "supplierID": "010",
        "supplierName": "OrganicHarvest",
        "email": "organicharvest@example.com",
        "phone": "123-456-7899",
        "contractStatus": "active",
        "startDate": "2023-04-05",
        "endDate": "2025-04-05"
    }
]
;

export const employees = [
    {
        "firstName": "John",
        "lastName": "Doe",
        "email": "johndoe@example.com",
        "role": "Cook",
        "phone": "1234567890",
        "fullTimePartTime": "fulltime",
        "department": "Kitchen",
        "startDate": "2023-01-15"
    },
    {
        "firstName": "Jane",
        "lastName": "Smith",
        "email": "janesmith@example.com",
        "role": "Waiter",
        "phone": "1234567891",
        "fullTimePartTime": "parttime",
        "department": "Dining",
        "startDate": "2023-02-20"
    },
    {
        "firstName": "Alice",
        "lastName": "Johnson",
        "email": "alicejohnson@example.com",
        "role": "Manager",
        "phone": "1234567892",
        "fullTimePartTime": "fulltime",
        "department": "Administration",
        "startDate": "2023-03-25"
    },
    {
        "firstName": "Bob",
        "lastName": "Brown",
        "email": "bobbrown@example.com",
        "role": "Cleaner",
        "phone": "1234567893",
        "fullTimePartTime": "parttime",
        "department": "Maintenance",
        "startDate": "2023-04-10"
    },
    {
        "firstName": "Charlie",
        "lastName": "Wilson",
        "email": "charliewilson@example.com",
        "role": "Chef",
        "phone": "1234567894",
        "fullTimePartTime": "fulltime",
        "department": "Kitchen",
        "startDate": "2023-05-05"
    },
    {
        "firstName": "Emily",
        "lastName": "Davis",
        "email": "emilydavis@example.com",
        "role": "Bartender",
        "phone": "1234567895",
        "fullTimePartTime": "fulltime",
        "department": "Bar",
        "startDate": "2023-06-15"
    },
    {
        "firstName": "Frank",
        "lastName": "Garcia",
        "email": "frankgarcia@example.com",
        "role": "Security",
        "phone": "1234567896",
        "fullTimePartTime": "fulltime",
        "department": "Security",
        "startDate": "2023-07-25"
    },
    {
        "firstName": "Grace",
        "lastName": "Harris",
        "email": "graceharris@example.com",
        "role": "Hostess",
        "phone": "1234567897",
        "fullTimePartTime": "parttime",
        "department": "Front Desk",
        "startDate": "2023-08-30"
    },
    {
        "firstName": "Henry",
        "lastName": "Martinez",
        "email": "henrymartinez@example.com",
        "role": "Server",
        "phone": "1234567898",
        "fullTimePartTime": "parttime",
        "department": "Dining",
        "startDate": "2023-09-10"
    },
    {
        "firstName": "Ivy",
        "lastName": "Clark",
        "email": "ivyclark@example.com",
        "role": "Sous Chef",
        "phone": "1234567899",
        "fullTimePartTime": "fulltime",
        "department": "Kitchen",
        "startDate": "2023-10-20"
    }
];


export const events = [
    {
        "EventName": "Smith-Jones Wedding",
        "CustomerFirstName": "Emily",
        "CustomerLastName": "Smith",
        "CustomerPhoneNumber": "1234567890",
        "CustomerEmail": "emily.smith@example.com",
        "EventType": "Wedding",
        "NumberOfGuests": 55,
        "EventDate": "2024-08-01",
        "StartTime": "16:00",
        "EndTime": "19:00",
        "VenueName": "Grand Plaza",
        "VenueStreetAddress": "123 Main Street",
        "VenueCity": "New York",
        "id": 4,
        "ingredients": []
    },
    {
        "EventName": "Johnson's 50th Birthday",
        "CustomerFirstName": "Michael",
        "CustomerLastName": "Johnson",
        "CustomerPhoneNumber": "1234567891",
        "CustomerEmail": "michael.johnson@example.com",
        "EventType": "Birthday",
        "NumberOfGuests": 30,
        "EventDate": "2024-07-22",
        "StartTime": "14:00",
        "EndTime": "17:00",
        "VenueName": "Sunset Hall",
        "VenueStreetAddress": "456 Elm Street",
        "VenueCity": "Los Angeles",
        "id": 5,
        "ingredients": []
    },
    {
        "EventName": "Tech Innovators Conference",
        "CustomerFirstName": "Sarah",
        "CustomerLastName": "Williams",
        "CustomerPhoneNumber": "1234567892",
        "CustomerEmail": "sarah.williams@example.com",
        "EventType": "Conference",
        "NumberOfGuests": 100,
        "EventDate": "2024-07-15",
        "StartTime": "09:00",
        "EndTime": "17:00",
        "VenueName": "Tech Center",
        "VenueStreetAddress": "789 Oak Avenue",
        "VenueCity": "Chicago",
        "id": 6,
        "ingredients": []
    },
    {
        "EventName": "Golden Anniversary Party",
        "CustomerFirstName": "David",
        "CustomerLastName": "Brown",
        "CustomerPhoneNumber": "1234567893",
        "CustomerEmail": "david.brown@example.com",
        "EventType": "Anniversary",
        "NumberOfGuests": 40,
        "EventDate": "2024-07-20",
        "StartTime": "18:00",
        "EndTime": "21:00",
        "VenueName": "Crystal Ballroom",
        "VenueStreetAddress": "321 Maple Lane",
        "VenueCity": "Houston",
        "id": 7,
        "ingredients": []
    },
    {
        "EventName": "Board Meeting",
        "CustomerFirstName": "Linda",
        "CustomerLastName": "Jones",
        "CustomerPhoneNumber": "1234567894",
        "CustomerEmail": "linda.jones@example.com",
        "EventType": "Meeting",
        "NumberOfGuests": 20,
        "EventDate": "2024-08-25",
        "StartTime": "10:00",
        "EndTime": "12:00",
        "VenueName": "Corporate Office",
        "VenueStreetAddress": "654 Pine Road",
        "VenueCity": "Miami",
        "id": 8,
        "ingredients": []
    },
    {
        "EventName": "Healthcare Seminar",
        "CustomerFirstName": "James",
        "CustomerLastName": "Garcia",
        "CustomerPhoneNumber": "1234567895",
        "CustomerEmail": "james.garcia@example.com",
        "EventType": "Seminar",
        "NumberOfGuests": 75,
        "EventDate": "2024-08-30",
        "StartTime": "13:00",
        "EndTime": "17:00",
        "VenueName": "Wellness Center",
        "VenueStreetAddress": "987 Cedar Boulevard",
        "VenueCity": "Dallas",
        "id": 9,
        "ingredients": []
    },
    {
        "EventName": "Summer Beach Party",
        "CustomerFirstName": "Jessica",
        "CustomerLastName": "Miller",
        "CustomerPhoneNumber": "1234567896",
        "CustomerEmail": "jessica.miller@example.com",
        "EventType": "Party",
        "NumberOfGuests": 50,
        "EventDate": "2024-08-05",
        "StartTime": "19:00",
        "EndTime": "23:00",
        "VenueName": "Seaside Resort",
        "VenueStreetAddress": "111 Birch Drive",
        "VenueCity": "San Francisco",
        "id": 10,
        "ingredients": []
    },
    {
        "EventName": "Art & Craft Workshop",
        "CustomerFirstName": "Robert",
        "CustomerLastName": "Martinez",
        "CustomerPhoneNumber": "1234567897",
        "CustomerEmail": "robert.martinez@example.com",
        "EventType": "Workshop",
        "NumberOfGuests": 25,
        "EventDate": "2024-08-10",
        "StartTime": "08:00",
        "EndTime": "12:00",
        "VenueName": "Creative Space",
        "VenueStreetAddress": "222 Willow Street",
        "VenueCity": "Seattle",
        "id": 11,
        "ingredients": []
    },
    {
        "EventName": "Charity Gala",
        "CustomerFirstName": "Jennifer",
        "CustomerLastName": "Davis",
        "CustomerPhoneNumber": "1234567898",
        "CustomerEmail": "jennifer.davis@example.com",
        "EventType": "Gala",
        "NumberOfGuests": 150,
        "EventDate": "2024-09-15",
        "StartTime": "18:00",
        "EndTime": "23:00",
        "VenueName": "Regal Hall",
        "VenueStreetAddress": "333 Ash Court",
        "VenueCity": "Las Vegas",
        "id": 12,
        "ingredients": []
    },
    {
        "EventName": "Art Exhibition",
        "CustomerFirstName": "William",
        "CustomerLastName": "Lopez",
        "CustomerPhoneNumber": "1234567899",
        "CustomerEmail": "william.lopez@example.com",
        "EventType": "Exhibition",
        "NumberOfGuests": 200,
        "EventDate": "2024-10-20",
        "StartTime": "09:00",
        "EndTime": "18:00",
        "VenueName": "Art Gallery",
        "VenueStreetAddress": "444 Poplar Avenue",
        "VenueCity": "Washington",
        "id": 13,
        "ingredients": []
    }
];